### ISSUE TITLE
Introduce base Exception class for entire library

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/openid-token-proxy#10]
From http://ruby-doc.org/core-2.1.1/Exception.html:

> It is recommended that a library should have one subclass of StandardError or RuntimeError and have specific exception types inherit from it. This allows the user to rescue a generic exception type to catch all exceptions the library may raise even if future versions of the library add new exception subclasses.

**Comment by timkurvers** [comment]
One thing I couldn't really find any clear seem to figure out is whether we should roll with `Exception` or `Error`.

**Comment by sindrenm** [comment]
I'd go with Error in Ruby.
